# version: "3.8"

services:
  vault-1:
    image: hashicorp/vault:1.15
    container_name: vault-1
    hostname: vault-1
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8200"
    volumes:
      - ./vault-1/config:/vault/config
      - ./vault-1/data:/vault/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-net

  vault-2:
    image: hashicorp/vault:1.15
    container_name: vault-2
    hostname: vault-2
    cap_add:
      - IPC_LOCK
    ports:
      - "8202:8200"
    volumes:
      - ./vault-2/config:/vault/config
      - ./vault-2/data:/vault/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-net

  vault-3:
    image: hashicorp/vault:1.15
    container_name: vault-3
    hostname: vault-3
    cap_add:
      - IPC_LOCK
    ports:
      - "8203:8200"
    volumes:
      - ./vault-3/config:/vault/config
      - ./vault-3/data:/vault/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - vault-net

networks:
  vault-net:
    external: true
