apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami-traefik
  # namespace: whoami
spec:
  parentRefs:
    - name: traefik-gateway # Name of the Gateway that Traefik creates when you enable the Gateway API provider
      namespace: traefik # Gateway가 있는 네임스페이스 (보통 Gateway는 공유됨)
  hostnames:
    - "whoami-traefik.club012.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: whoami
          port: 80
